# Generated by Django 3.0.8 on 2020-07-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='completed_courses',
            field=models.ManyToManyField(null=True, related_name='answers', to='Cursos.Course'),
        ),
    ]
