# Generated by Django 3.0.8 on 2020-07-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0002_auto_20200702_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='Cursos.Course'),
        ),
    ]
