# Generated by Django 3.0.8 on 2020-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_auto_20200702_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
