# Generated by Django 3.0.8 on 2020-07-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_profilelesson_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answerO',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answerB',
        ),
    ]
